zed_front_serial: 37963597
zed_rear_serial: 31061594

# Velodyne network/settings for James.
# To test a different spin rate, change rpm here, for example 650.0.
velodyne:
  model: "VLP16"
  rpm: 600.0
  device_ip: "192.168.1.201"
  port: 2368
  frame_id: "velodyne"

lidar_tf:
  parent_frame: "base_link"
  child_frame: "velodyne"
  x: 1.524
  y: 0.0254
  z: 1.778
  roll: 0.0
  pitch: 0.0
  yaw: 0.0
