## Summary

Describe the technical change or feature.

---

## Motivation

Why is this necessary for the cart or project?

---

## Success Metrics (REQUIRED)

How will we objectively verify this is complete?

Be specific:

- What command will be run?
- What output/topic/log confirms success?
- What physical behavior confirms success?

Example format:

1. Run: `ros2 launch ...`

2. Expected observable behavior:
- ...
3. Expected topic output:
- ...

---

## Demo Plan (REQUIRED)

Describe exactly how you will demonstrate completion.

---

## Risks / Dependencies

Anything that could break existing systems?